Add timeout parameter to context.call
upstash/workflow-js pull request #31
Opened 2024-11-26 09:25 UTC by CahidArda

Also add an error when step name is undefined or empty string

2024-11-28 08:55 UTC, fahreddinozcan commented on src/context/context.ts
> +   * @param timeout max duration to wait for the endpoint to respond
Can we add the unit to jsdocs here?

2024-11-29 07:07 UTC, fahreddinozcan approved these changes

2024-11-29 08:01 UTC, joschan21 requested changes
let's make the error message a bit more clear, otherwise LGTM

2024-11-29 08:01 UTC, joschan21 commented on src/context/steps.ts
> +      throw new WorkflowError("step name can't be undefined or empty string.");
A workflow step name cannot be undefined or an empty string. Please provide a name for your workflow step.

2024-12-03 06:26 UTC, merged